

# ------------------------------------------ Base

gem 'unicorn-rails'

# ------------------------------------------ Assets

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'bones-rails'
gem 'bourbon'
gem 'backbone-on-rails'
gem "jquery-fileupload-rails"

# ------------------------------------------ View Helpers

gem 'jbuilder'
gem 'simple_form'
gem 'wysihtml5-rails'
gem 'pickadate-rails'

# ------------------------------------------ Utilities

gem 'ancestry'
gem 'cambium'
gem 'devise'
gem 'carrierwave'
gem 'hirb'

# ------------------------------------------ Development/Test

group :development do
  gem 'annotate'
end

gem 'factory_girl_rails'
gem 'faker'

# ------------------------------------------ User Gems
